sudo: false
language: node_js
node_js:
  - stable
install:
  - npm install
addons:
  apt:
    packages:
      # cypress told me I need it: https://docs.cypress.io/guides/guides/continuous-integration.html#Travis
      - libgconf-2-4
cache:
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
notifications:
  email: false
branches:
  only:
    - master
script:
  - npm run lint
  - npm run test
  - npm run coveralls
after_success:
  - npx codecov
